export interface Plant {
  id?: string;          // optional, auto-generated by backend
  name: string;         // plant/flower name
  description: string;  // details about the plant
  price: number;        // price in LKR/USD
  category?: string;    // flower | plant | package
  imageUrl?: string;    // photo URL
}
